Progress bar feature
your-tools/python-cli-ui pull request #64
Opened 2021-04-20 08:33 UTC by Maofryy

# New Feature
Changes proposed in this pull request:
 ```python
info_progress_bar(prefix: str, value: float, max_value: float)
```
Adding to ```info_progress``` a progress bar with ascii character "█" between prefix and percent

2021-04-20 14:05 UTC, dmerejkowsky commented
Looks like a good addition, but there are a few problems:

* Tests are missing
* The code does not seem to work on my machine

![screenshot](https://user-images.githubusercontent.com/606755/115409271-e10f5200-a1f1-11eb-9168-e2d5b023d78c.png)

* I fear it would not work on Windows (I need to check)
* Finally, there's already a pretty good library for that called `tqdm` which complements `cli_ui` nicely I think

2021-04-20 14:05 UTC, dmerejkowsky requested changes

2021-04-20 14:05 UTC, dmerejkowsky commented on cli_ui/__init__.py
> +            spaces = int(-1 * (max_value*2 - int(value*2)) // 1 * -1)*" ",
This would be easier to read with the introduction of a few intermediary variables and a few comments

2021-04-20 15:01 UTC, Maofryy commented
- I implemented tests and needed to change the function to do so. Its passing fine, still tests fails on windows not recognizing colored text.
-  Previously I had a dynamic size depending on the ```max_value``` but now i fixed it so the bar has only ```MAX_SIZE``` characters
- I tested it manually on ```cmd.exe``` and it is working.
- I was inspired by the ```tqdm.tqdm``` module yes, but I want to mix the two librairies by displaying a progress bar with different colors according to progress (dark red at 0% into bright green at 100%) but I still need to think about its implementation and tests (here on my windows the colored tests are failing).

2021-04-20 16:44 UTC, Maofryy commented
* Merged #65 with the current pr
* Implemented rather bluntly a red-green gradient to the progress bar, scaling with the ```MAX_SIZE``` (maybe add the max_size as an argument ?)
* Updated test to work with color

2021-05-01 12:36 UTC, dmerejkowsky commented
Hello again.

I've just merged a bunch of stuff in the main branch - so you should incorporate them in your PR.

You can do it by rebasing your branch on top of `origin/master` and force-push this branch (this will be easier to review that way).

You ll see that the linters have caught a few additional errors, like this:

```
cli_ui/__init__.py:357:51: N803 argument name 'fileObj' should be lowercase
``` 

so you'll have to fix them too.

Also, you should add a call to `progress_bar` in `main_demo`, and add a section about it in the documentation.

Finally, you should update the changelog.

2021-05-01 12:36 UTC, dmerejkowsky commented
Oh - and also found a crash:

```
  File "/mnt/data/dmerej/src/python-cli-ui/cli_ui/__init__.py", line 712, in main_demo
    info_progress_bar("Progress", 1000, 100)
  File "/mnt/data/dmerej/src/python-cli-ui/cli_ui/__init__.py", line 383, in info_progress_bar
    color = COLOR_LIST[int(percent / 12.5)]
IndexError: list index out of range
```

2021-05-01 12:47 UTC, dmerejkowsky requested changes

2021-05-01 12:47 UTC, dmerejkowsky commented on cli_ui/__init__.py
> +    color = COLOR_LIST[int(percent / 12.5)]
* this won' t work if percent is bigger than 100
* not sure why yo go through a percentage anyway. You can just use ration =value / max_value
* don' t hard-code 12.5 - use len(COLOR_LIST) instead

2021-05-01 12:47 UTC, dmerejkowsky commented on cli_ui/__init__.py
> +    MAX_SIZE = 10
rename to `bar_length` ?

2021-05-01 12:47 UTC, dmerejkowsky commented on cli_ui/__init__.py
> +    if fileObj.isatty():
I think you can use the `colors_enabled`  and the `write_and_flush`  helper methods here

2022-05-14 12:52 UTC, closed without merging